"""add Comment author

Revision ID: df689eab6d98
Revises: ad1830054dd4
Create Date: 2021-03-03 17:56:37.038258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df689eab6d98'
down_revision = 'ad1830054dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'author')
    # ### end Alembic commands ###
